Repository alicenet/ui, pull requests merged in 2022-11, with the labels that each got.

#76 Feat: add sx utility for conditional styles
  alca-app/src/pages/Transactions/Transactions.jsx
  alca-app/src/theme/MUITheme.js
  alca-app/src/utils/index.js
  alca-app/src/utils/sx.js
Labels: kind/feature

#86 Fix/alca app/config imports
  alca-lockup/src/eth/ethAdapter.js
  alca-lockup/src/redux/actions/application.js
  alca-migrate/src/components/alcaCalculator/AlcaCalculator.jsx
  alca-migrate/src/eth/ethAdapter.js
  alca-migrate/src/redux/actions/application.js
  alca-staking/src/eth/ethAdapter.js
  alca-staking/src/redux/actions/application.js
Labels: kind/bug

#100 feat: unstake position
  alca-app/src/components/SnackbarMessage.jsx
  alca-app/src/pages/Positions/Positions.jsx
  alca-app/src/pages/Transactions/Transactions.jsx
Labels: kind/feature

#119 chore: hide pagination for lockup position datagrid
  alca-app/src/pages/Positions/Positions.jsx
  alca-app/src/pages/Transactions/Transactions.jsx
Labels: kind/chore

#120 fix: disable lock switch when migrating mad to alca
  alca-app/src/pages/Transactions/Transactions.jsx
Labels: kind/bug
