Repository alicenet/ui, pull requests merged in 2023-02, with the labels that each got.

#180 feat: ini ttt
  hw-tictac/.gitignore
  hw-tictac/README.md
  hw-tictac/artifacts/Storage.json
  hw-tictac/dotenv
  hw-tictac/jsconfig.json
  hw-tictac/package.json
  hw-tictac/public/favicon.ico
  hw-tictac/public/index.html
  hw-tictac/public/logo192.png
  hw-tictac/public/logo512.png
  hw-tictac/public/manifest.json
  hw-tictac/public/robots.txt
  hw-tictac/src/App.js
  hw-tictac/src/assets/Logo.svg
  hw-tictac/src/assets/eth-diamond-purple.png
  hw-tictac/src/components/ConnectWeb3Button.jsx
  hw-tictac/src/components/Copyright.jsx
  hw-tictac/src/components/NavigationBar.jsx
  hw-tictac/src/components/index.js
  hw-tictac/src/config/_config.js
  hw-tictac/src/config/index.js
  hw-tictac/src/config/pageConfiguration.js
  hw-tictac/src/index.js
  hw-tictac/src/pages/Home/Home.jsx
  hw-tictac/src/pages/index.js
  hw-tictac/src/redux/actions/application.js
  hw-tictac/src/redux/actions/index.js
  hw-tictac/src/redux/constants/application.js
  hw-tictac/src/redux/constants/index.js
  hw-tictac/src/redux/reducers/application.js
  hw-tictac/src/redux/reducers/index.js
  hw-tictac/src/redux/store/store.js
  hw-tictac/src/style/index.css
  hw-tictac/src/theme/MUITheme.js
  hw-tictac/src/utils/index.js
  hw-tictac/src/utils/string.js
  package.json
Labels: kind/feature

#186 Update branch
  hw-tictac/src/components/page/Page.jsx
  hw-tictac/src/components/playTicTacToe/PlayTicTacToe.jsx
  hw-tictac/src/components/ticTacToeBoard/TicTacToeBoard.jsx
  hw-tictac/src/components/walletComposition/WalletComposition.jsx
Labels: kind/chore

#185 Patch monorepo dependencies
  .eslintrc.json
  hw-tictac/config-overrides.js
  hw-tictac/craco.config.js
  hw-tictac/package.json
  hw-tictac/src/App.js
  hw-tictac/src/components/header/Header.jsx
  hw-tictac/src/components/header/HeaderMobile.jsx
  hw-tictac/src/components/proofOfConcept/ProofOfConcept.jsx
  hw-tictac/src/config/config.js
  hw-tictac/src/index.js
  hw-tictac/yarn.lock
Labels: kind/bug

#187 Tt logistics
  .eslintrc.json
  hw-tictac/package.json
  hw-tictac/src/components/board/Board.jsx
  hw-tictac/src/components/header/WalletDropdown.jsx
  hw-tictac/src/components/playTicTacToe/PlayTicTacToe.jsx
  hw-tictac/src/components/statusOverlay/StatusOverlay.jsx
  hw-tictac/src/components/ticTacToeBoard/TicTacToeBoard.jsx
  hw-tictac/src/components/walletComposition/WalletComposition.jsx
  hw-tictac/src/config/config.js
  hw-tictac/src/redux/actions.js
  hw-tictac/src/redux/gameState.js
  hw-tictac/src/redux/reducers.js
  hw-tictac/src/redux/store.js
  hw-tictac/src/utils/generic.js
  hw-tictac/yarn.lock
Labels: kind/feature

#190 chore: additional logic
  hw-tictac/src/components/playTicTacToe/PlayTicTacToe.jsx
  hw-tictac/src/components/ticTacToeBoard/TicTacToeBoard.jsx
  hw-tictac/src/components/walletComposition/WalletComposition.jsx
  hw-tictac/src/redux/actions.js
  hw-tictac/src/redux/gameState.js
  hw-tictac/src/redux/reducers.js
Labels: kind/chore
